# Generated by Django 6.0.6 on 2026-06-23 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='Category',
        ),
    ]
