# Generated by Django 6.0.6 on 2026-07-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_coupon_rename_category_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Subcategory',
            new_name='subcategory',
        ),
    ]
