# Generated by Django 6.0.6 on 2026-07-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='Category',
            new_name='category',
        ),
    ]
