# Generated by Django 6.0.6 on 2026-07-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_delivery_time_productvariant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='original_price',
            new_name='cut_price',
        ),
    ]
