# Generated by Django 6.0.6 on 2026-08-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
