# Generated by Django 6.0.6 on 2026-09-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order_status_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(default=0, help_text='0 daaloge to OFF nahi dikhega,20 daaloge to 20% OFF'),
        ),
    ]
