# Generated by Django 6.0.6 on 2026-09-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='cut_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
