# Generated by Django 6.0.6 on 2026-09-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_coupon_min_order_amount_alter_coupon_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='coupon',
            name='expired_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
