# Generated by Django 6.0.6 on 2026-09-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_add_cash_received_to_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khataentry',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='wallet_used',
        ),
        migrations.DeleteModel(
            name='KhataCustomer',
        ),
        migrations.DeleteModel(
            name='KhataEntry',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
