# Generated by Django 6.0.6 on 2026-09-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_flash_deal',
            field=models.BooleanField(default=False),
        ),
    ]
