# Generated by Django 6.0.6 on 2026-09-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_product_flash_end_time_product_is_flash_deal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount_percent',
            new_name='discount_value',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='min_amount',
            new_name='min_order_amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='expired_date',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_from',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('Flat', 'Flat')], default='Percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_usage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
