from django.urls import path
from . import views
from django.shortcuts import redirect

urlpatterns = [
    path('', views.home, name='home'),
    path('search/',views.search_products, name='search_products'),
    path('add/<int:product_id>/',views.add_to_cart,name='add_to_cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart_alias'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='cart_add'),
    path('cart/',views.cart_view,name='cart_view'),
    path('clear-all/',lambda request:(request.session.flush(), redirect('cart_view'))[1]),
    path('update/<str:cart_key>/<str:action>/', views.update_cart, name="update_cart"),
    path('checkout/', views.checkout, name='checkout'),
    path('login/',views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/',views.register_view,name='register'),
    path('forgot-password/', views.forgot_password_view, name='forgot_password'),
    path('admin-login/',views.admin_login_view, name='admin_login'),
    path('admin-forgot-password/', views.admin_forgot_password_view, name='admin_forgot_password'),
    path('dashboard/',views.admin_dashboard, name='admin_dashboard'),
    path('admin-orders/', views.admin_orders, name='admin_orders'),
    path('dashboard/order/<int:order_id>/clear-due/', views.clear_order_due, name='clear_order_due'),
    path('product/add/', views.add_product, name='add_product'),
    path('product/update/<int:pk>',views.update_product, name='update_product'), #pk=product id
    path('product/delete/<int:pk>',views.delete_product, name='delete_product'),
    path('bill/', views.bill_view,name='bill'), 
    path('bill/<int:order_id>/',views.bill_view,name='bill_detail'),
    path('record-cash/<int:order_id>/', views.record_cash_payment, name='record_cash_payment'),
    path('product/<int:id>/', views.product_detail, name='product_detail'),
    path('product/<int:product_id>/rate/', views.rate_product, name='rate_product'),
    path('cart/apply-coupon/',views.apply_coupon,name='apply_coupon'),
    path('account/login/',views.login_view, name='login'),
    path('order-success/',views.order_success, name='order_success'),
    path('my-orders/', views.my_orders_view, name='my_orders'),
    path('my-bills/', views.my_bills_view, name='my_bills'),
    path('delete-bill/<int:order_id>/', views.delete_bill, name='delete_bill'),
    path('cart/update/<str:key>/', views.update_qty, name='update_qty'),
    path('dashboard/add-category/', views.add_category, name='add_category'),
    path('dashboard/add-subcategory/', views.add_subcategory, name='add_subcategory'),
    path('dashboard/delete-category/<int:id>/', views.delete_category, name='delete_category'),
    path('dashboard/edit-category/<int:id>/', views.edit_category, name='edit_category'),
    path('dashboard/edit-subcategory/<int:id>/', views.edit_subcategory, name='edit_subcategory'),
    path('dashboard/delete-subcategory/<int:id>/', views.delete_subcategory, name='delete_subcategory'),
    path('dashboard/coupons/', views.dashboard_coupons, name='dashboard_coupons'),
    path('dashboard/coupons/add/', views.dashboard_add_coupon, name='dashboard_add_coupon'),
    path('dashboard/coupons/edit/<int:id>/', views.dashboard_edit_coupon, name='dashboard_edit_coupon'),
    path('dashboard/coupons/delete/<int:id>/', views.dashboard_delete_coupon, name='dashboard_delete_coupon'),
    path('cancel-order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('admin-logins/', views.admin_logins, name='admin_logins'),
    path('customer-logout/', views.customer_logout, name='customer_logout'),
    path('admin-logout/', views.admin_logout, name='admin_logout'),
    path('wishlist/', views.wishlist_view, name='wishlist_view'),
    path('wishlist/add/<int:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<int:product_id>/', views.remove_from_wishlist, name='remove_from_wishlist'),

]
